### PR TITLE
fix: `alg` is nothing

### LINKED ISSUE #1027: ERROR: LoadError: MethodError: no method matching forwarddiffs_model_time(::Nothing)
**Describe the bug 🐞**

AD with `DifferentialEquations` and without `alg` is passing `nothing` as `alg` to `forwarddiffs_model_time`

**Expected behavior**

It should work with or without an `alg`.

**Minimal Reproducible Example 👇**

```julia
using ComponentArrays, DifferentialEquations, Lux, Random, SciMLSensitivity, Zygote

function f(du, u, p, t)
    du .= first(nn(u, p, st))
    nothing
end

nn = Dense(8, 8, tanh)
ps, st = Lux.setup(Random.default_rng(), nn)
ps = ComponentArray(ps)

r = rand(Float32, 8, 64)

function f2(x)
    prob = ODEProblem(f, r, (0.0f0, 1.0f0), x)
    sol = solve(prob; sensealg = InterpolatingAdjoint(; autodiff = true, autojacvec = true))
    sum(last(sol.u))
end

f2(ps)
Zygote.gradient(f2, ps)
```

**Error & Stacktrace ⚠️**

```julia
ERROR: LoadError: MethodError: no method matching forwarddiffs_model_time(::Nothing)

Closest candidates are:
  forwarddiffs_model_time(::Union{OrdinaryDiffEq.OrdinaryDiffEqRosenbrockAdaptiveAlgorithm, OrdinaryDiffEq.OrdinaryDiffEqRosenbrockAlgorithm})
   @ OrdinaryDiffEq C:\Users\Hossein Pourbozorg\.julia\packages\OrdinaryDiffEq\DmspS\src\alg_utils.jl:22
  forwarddiffs_model_time(::SciMLBase.AbstractSciMLAlgorithm)
   @ SciMLBase C:\Users\Hossein Pourbozorg\.julia\packages\SciMLBase\Dwomw\src\alg_traits.jl:32

Stacktrace:
  [1] adjointdiffcache(g::Nothing, sensealg::InterpolatingAdjoint{…}, discrete::Bool, sol::ODESolution{…}, dgdu::Nothing, dgdp::Nothing, f::ODEFunction{…}, alg::Nothing; quad::Bool, noiseterm::Bool, needs_jac::Bool)
    @ SciMLSensitivity C:\Users\Hossein Pourbozorg\.julia\packages\SciMLSensitivity\Jk0Zp\src\adjoint_common.jl:107
  [2] SciMLSensitivity.ODEInterpolatingAdjointSensitivityFunction(g::Nothing, sensealg::InterpolatingAdjoint{…}, discrete::Bool, sol::ODESolution{…}, dgdu::Nothing, dgdp::Nothing, f::ODEFunction{…}, alg::Nothing, checkpoints::Vector{…}, tols::@NamedTuple{…}, tstops::Nothing; noiseterm::Bool, tspan::Tuple{…})
    @ SciMLSensitivity C:\Users\Hossein Pourbozorg\.julia\packages\SciMLSensitivity\Jk0Zp\src\interpolating_adjoint.jl:87
  [3] ODEAdjointProblem(sol::ODESolution{…}, sensealg::InterpolatingAdjoint{…}, alg::Nothing, t::Vector{…}, dgdu_discrete::SciMLSensitivity.var"#df_iip#308"{…}, dgdp_discrete::Nothing, dgdu_continuous::Nothing, dgdp_continuous::Nothing, g::Nothing, ::Val{…}; checkpoints::Vector{…}, callback::Nothing, reltol::Float64, abstol::Float64, kwargs::@Kwargs{…})
    @ SciMLSensitivity C:\Users\Hossein Pourbozorg\.julia\packages\SciMLSensitivity\Jk0Zp\src\interpolating_adjoint.jl:337
  [4] _adjoint_sensitivities(sol::ODESolution{…}, sensealg::InterpolatingAdjoint{…}, alg::Nothing; t::Vector{…}, dgdu_discrete::Function, dgdp_discrete::Nothing, dgdu_continuous::Nothing, dgdp_continuous::Nothing, g::Nothing, abstol::Float64, reltol::Float64, checkpoints::Vector{…}, corfunc_analytical::Nothing, callback::Nothing, kwargs::@Kwargs{…})
    @ SciMLSensitivity C:\Users\Hossein Pourbozorg\.julia\packages\SciMLSensitivity\Jk0Zp\src\sensitivity_interface.jl:406
  [5] adjoint_sensitivities(sol::ODESolution{…}, args::Nothing; sensealg::InterpolatingAdjoint{…}, verbose::Bool, kwargs::@Kwargs{…})
    @ SciMLSensitivity C:\Users\Hossein Pourbozorg\.julia\packages\SciMLSensitivity\Jk0Zp\src\sensitivity_interface.jl:386
  [6] (::SciMLSensitivity.var"#adjoint_sensitivity_backpass#307"{…})(Δ::ODESolution{…})
    @ SciMLSensitivity C:\Users\Hossein Pourbozorg\.julia\packages\SciMLSensitivity\Jk0Zp\src\concrete_solve.jl:536
  [7] ZBack
    @ C:\Users\Hossein Pourbozorg\.julia\packages\Zygote\jxHJc\src\compiler\chainrules.jl:211 [inlined]
  [8] (::Zygote.var"#291#292"{…})(Δ::ODESolution{…})
    @ Zygote C:\Users\Hossein Pourbozorg\.julia\packages\Zygote\jxHJc\src\lib\lib.jl:206
  [9] (::Zygote.var"#2169#back#293"{…})(Δ::ODESolution{…})
    @ Zygote C:\Users\Hossein Pourbozorg\.julia\packages\ZygoteRules\M4xmc\src\adjoint.jl:72
 [10] #solve#41
    @ C:\Users\Hossein Pourbozorg\.julia\packages\DiffEqBase\8vI1R\src\solve.jl:1003 [inlined]
 [11] (::Zygote.Pullback{Tuple{…}, Any})(Δ::ODESolution{Float32, 3, Vector{…}, Nothing, Nothing, Vector{…}, Nothing, ODEProblem{…}, CompositeAlgorithm{…}, SciMLBase.LinearInterpolation{…}, Nothing, Nothing})
    @ Zygote C:\Users\Hossein Pourbozorg\.julia\packages\Zygote\jxHJc\src\compiler\interface2.jl:0
 [12] #291
    @ C:\Users\Hossein Pourbozorg\.julia\packages\Zygote\jxHJc\src\lib\lib.jl:206 [inlined]
 [13] (::Zygote.var"#2169#back#293"{…})(Δ::ODESolution{…})
    @ Zygote C:\Users\Hossein Pourbozorg\.julia\packages\ZygoteRules\M4xmc\src\adjoint.jl:72
 [14] solve
    @ C:\Users\Hossein Pourbozorg\.julia\packages\DiffEqBase\8vI1R\src\solve.jl:993 [inlined]
 [15] (::Zygote.Pullback{Tuple{…}, Any})(Δ::ODESolution{Float32, 3, Vector{…}, Nothing, Nothing, Vector{…}, Nothing, ODEProblem{…}, CompositeAlgorithm{…}, SciMLBase.LinearInterpolation{…}, Nothing, Nothing})
    @ Zygote C:\Users\Hossein Pourbozorg\.julia\packages\Zygote\jxHJc\src\compiler\interface2.jl:0
 [16] f2
    @ C:\Users\Hossein Pourbozorg\Code Projects\Mine\Bug Report\br-2\br-2.jl:16 [inlined]
 [17] (::Zygote.Pullback{Tuple{…}, Tuple{…}})(Δ::Float32)
    @ Zygote C:\Users\Hossein Pourbozorg\.julia\packages\Zygote\jxHJc\src\compiler\interface2.jl:0
 [18] (::Zygote.var"#75#76"{Zygote.Pullback{Tuple{…}, Tuple{…}}})(Δ::Float32)
    @ Zygote C:\Users\Hossein Pourbozorg\.julia\packages\Zygote\jxHJc\src\compiler\interface.jl:91
 [19] gradient(f::Function, args::ComponentVector{Float32, Vector{Float32}, Tuple{Axis{(weight = ViewAxis(1:64, ShapedAxis((8, 8))), bias = ViewAxis(65:72, ShapedAxis((8, 1))))}}})
    @ Zygote C:\Users\Hossein Pourbozorg\.julia\packages\Zygote\jxHJc\src\compiler\interface.jl:148
 [20] top-level scope
    @ C:\Users\Hossein Pourbozorg\Code Projects\Mine\Bug Report\br-2\br-2.jl:21
 [21] include(fname::String)
    @ Base.MainInclude .\client.jl:489
 [22] top-level scope
    @ REPL[1]:1
in expression starting at C:\Users\Hossein Pourbozorg\Code Projects\Mine\Bug Report\br-2\br-2.jl:21
Some type information was truncated. Use `show(err)` to see complete types.
```

**Environment (please complete the following information):**

  - Output of `using Pkg; Pkg.status()`

```julia
Status `C:\Users\Hossein Pourbozorg\Code Projects\Mine\Bug Report\br-2\Project.toml`
  [b0b7db55] ComponentArrays v0.15.10
  [0c46a032] DifferentialEquations v7.13.0
  [b2108857] Lux v0.5.22
  [1ed8b502] SciMLSensitivity v7.56.0
  [e88e6eb3] Zygote v0.6.69
  [9a3f8284] Random
```

  - Output of `using Pkg; Pkg.status(; mode = PKGMODE_MANIFEST)`

```julia
Status `C:\Users\Hossein Pourbozorg\Code Projects\Mine\Bug Report\br-2\Manifest.toml`
  [47edcb42] ADTypes v0.2.6
  [621f4979] AbstractFFTs v1.5.0
  [79e6a3ab] Adapt v4.0.1
⌅ [ec485272] ArnoldiMethod v0.2.0
  [4fba245c] ArrayInterface v7.8.0
  [4c555306] ArrayLayouts v1.6.0
  [a9b6321e] Atomix v0.1.0
  [aae01518] BandedMatrices v1.5.0
  [6e4b80f9] BenchmarkTools v1.5.0
  [62783981] BitTwiddlingConvenienceFunctions v0.1.5
  [764a87c0] BoundaryValueDiffEq v5.6.3
  [fa961155] CEnum v0.5.0
  [2a0fbf3d] CPUSummary v0.2.4
  [49dc2e85] Calculus v0.5.1
  [7057c7e9] Cassette v0.3.13
  [082447d4] ChainRules v1.63.0
  [d360d2e6] ChainRulesCore v1.23.0
  [fb6a15b2] CloseOpenIntervals v0.1.12
  [523fee87] CodecBzip2 v0.8.2
  [944b1d66] CodecZlib v0.7.4
  [38540f10] CommonSolve v0.2.4
  [bbf7d656] CommonSubexpressions v0.3.0
  [34da2185] Compat v4.14.0
  [b0b7db55] ComponentArrays v0.15.10
  [2569d6c7] ConcreteStructs v0.2.3
  [187b0558] ConstructionBase v1.5.4
  [adafc99b] CpuId v0.3.1
  [9a962f9c] DataAPI v1.16.0
  [864edb3b] DataStructures v0.18.17
  [e2d170a0] DataValueInterfaces v1.0.0
  [bcd4f6db] DelayDiffEq v5.47.0
  [2b5f629d] DiffEqBase v6.148.0
  [459566f4] DiffEqCallbacks v3.3.0
  [77a26b50] DiffEqNoiseProcess v5.21.0
  [163ba53b] DiffResults v1.1.0
  [b552c78f] DiffRules v1.15.1
  [0c46a032] DifferentialEquations v7.13.0
  [b4f34e82] Distances v0.10.11
  [31c24e10] Distributions v0.25.107
  [ffbed154] DocStringExtensions v0.9.3
  [fa6b7ba4] DualNumbers v0.6.8
  [da5c29d0] EllipsisNotation v1.8.0
  [4e289a0a] EnumX v1.0.4
  [7da242da] Enzyme v0.11.17
⌅ [f151be2c] EnzymeCore v0.6.5
  [d4d017d3] ExponentialUtilities v1.26.1
  [e2ba6199] ExprTools v0.1.10
  [9d29842c] FastAlmostBandedMatrices v0.1.0
  [7034ab61] FastBroadcast v0.2.8
  [9aa1b823] FastClosures v0.3.2
  [29a986be] FastLapackInterface v2.0.2
  [1a297f60] FillArrays v1.9.3
  [6a86dc24] FiniteDiff v2.22.0
  [f6369f11] ForwardDiff v0.10.36
  [f62d2435] FunctionProperties v0.1.0
  [069b7b12] FunctionWrappers v1.1.3
  [77dc65aa] FunctionWrappersWrappers v0.1.3
  [d9f16b24] Functors v0.4.7
  [0c68f7d7] GPUArrays v10.0.2
  [46192b85] GPUArraysCore v0.1.6
⌅ [61eb1bfa] GPUCompiler v0.25.0
  [c145ed77] GenericSchur v0.5.3
  [86223c79] Graphs v1.9.0
  [3e5b6fbb] HostCPUFeatures v0.1.16
  [34004b35] HypergeometricFunctions v0.3.23
  [7869d1d1] IRTools v0.4.12
  [615f187c] IfElse v0.1.1
  [d25df0c9] Inflate v0.1.4
  [92d709cd] IrrationalConstants v0.2.2
  [82899510] IteratorInterfaceExtensions v1.0.0
  [692b3bcd] JLLWrappers v1.5.0
  [682c06a0] JSON v0.21.4
  [ccbc3e58] JumpProcesses v9.10.1
  [ef3ab10e] KLU v0.6.0
  [63c18a36] KernelAbstractions v0.9.17
  [ba0b0d4f] Krylov v0.9.5
  [929cbde3] LLVM v6.6.0
  [10f19ff3] LayoutPointers v0.1.15
  [5078a376] LazyArrays v1.8.3
  [2d8b4e74] LevyArea v1.0.0
  [d3d80556] LineSearches v7.2.0
  [7ed4a6bd] LinearSolve v2.26.0
  [2ab3a3ac] LogExpFunctions v0.3.27
  [bdcacae8] LoopVectorization v0.12.166
  [b2108857] Lux v0.5.22
  [bb33d45b] LuxCore v0.1.12
  [34f89e08] LuxDeviceUtils v0.1.16
  [82251201] LuxLib v0.3.10
  [1914dd2f] MacroTools v0.5.13
  [d125e4d3] ManualMemory v0.1.8
  [b8f27783] MathOptInterface v1.27.0
  [a3b82374] MatrixFactorizations v2.1.0
  [bb5d69b7] MaybeInplace v0.1.1
  [e1d29d7a] Missings v1.1.0
  [46d2c3a1] MuladdMacro v0.2.4
  [d8a4904e] MutableArithmetics v1.4.1
  [d41bc354] NLSolversBase v7.8.3
  [2774e3e8] NLsolve v4.5.1
  [872c559c] NNlib v0.9.12
  [77ba4419] NaNMath v1.0.2
  [8913a72c] NonlinearSolve v3.7.3
  [d8793406] ObjectFile v0.4.1
  [6fe1bfb0] OffsetArrays v1.13.0
  [429524aa] Optim v1.9.2
  [3bd65402] Optimisers v0.3.2
  [bac558e1] OrderedCollections v1.6.3
  [1dea7af3] OrdinaryDiffEq v6.74.0
  [90014a1f] PDMats v0.11.31
  [65ce6f38] PackageExtensionCompat v1.0.2
  [d96e819e] Parameters v0.12.3
  [69de0a69] Parsers v2.8.1
  [570af359] PartialFunctions v1.2.0
  [e409e4f3] PoissonRandom v0.4.4
  [f517fe37] Polyester v0.7.9
  [1d0040c9] PolyesterWeave v0.2.1
  [85a6dd25] PositiveFactorizations v0.2.4
  [d236fae5] PreallocationTools v0.4.20
  [aea7be01] PrecompileTools v1.2.0
  [21216c6a] Preferences v1.4.3
  [1fd47b50] QuadGK v2.9.4
  [74087812] Random123 v1.7.0
  [e6cf234a] RandomNumbers v1.5.3
  [c1ae055f] RealDot v0.1.0
  [3cdcf5f2] RecipesBase v1.3.4
  [731186ca] RecursiveArrayTools v3.10.1
  [f2c3362d] RecursiveFactorization v0.2.21
  [189a3867] Reexport v1.2.2
  [ae029012] Requires v1.3.0
  [ae5879a3] ResettableStacks v1.1.1
  [37e2e3b7] ReverseDiff v1.15.1
  [79098fc4] Rmath v0.7.1
  [7e49a35a] RuntimeGeneratedFunctions v0.5.12
  [94e857df] SIMDTypes v0.1.0
  [476501e8] SLEEFPirates v0.6.42
  [0bca4576] SciMLBase v2.29.0
  [c0aeaf25] SciMLOperators v0.3.8
  [1ed8b502] SciMLSensitivity v7.56.0
  [6c6a2e73] Scratch v1.2.1
  [efcf1570] Setfield v1.1.1
  [727e6d20] SimpleNonlinearSolve v1.5.0
  [699a6c99] SimpleTraits v0.9.4
  [ce78b400] SimpleUnPack v1.1.0
  [a2af1166] SortingAlgorithms v1.2.1
  [47a9eef4] SparseDiffTools v2.17.0
  [dc90abb0] SparseInverseSubset v0.1.2
  [e56a9233] Sparspak v0.3.9
  [276daf66] SpecialFunctions v2.3.1
  [aedffcd0] Static v0.8.10
  [0d7ed370] StaticArrayInterface v1.5.0
  [90137ffa] StaticArrays v1.9.3
  [1e83bf80] StaticArraysCore v1.4.2
  [82ae8749] StatsAPI v1.7.0
  [2913bbd2] StatsBase v0.34.2
  [4c63d2b9] StatsFuns v1.3.1
  [9672c7b4] SteadyStateDiffEq v2.1.0
  [789caeaf] StochasticDiffEq v6.65.1
  [7792a7ef] StrideArraysCore v0.5.2
  [09ab397b] StructArrays v0.6.18
  [53d494c1] StructIO v0.3.0
  [c3572dad] Sundials v4.24.0
  [2efcf032] SymbolicIndexingInterface v0.3.8
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.11.1
  [8290d209] ThreadingUtilities v0.5.2
  [a759f4b9] TimerOutputs v0.5.23
  [9f7883ad] Tracker v0.2.32
  [3bb67fe8] TranscodingStreams v0.10.3
  [d5829a12] TriangularSolve v0.1.20
  [410a4b4d] Tricks v0.1.8
  [781d530d] TruncatedStacktraces v1.4.0
  [3a884ed6] UnPack v1.0.2
  [013be700] UnsafeAtomics v0.2.1
  [d80eeb9a] UnsafeAtomicsLLVM v0.1.3
  [3d5dd08c] VectorizationBase v0.21.65
  [19fa3120] VertexSafeGraphs v0.2.0
  [d49dbf32] WeightInitializers v0.1.6
  [e88e6eb3] Zygote v0.6.69
  [700de1a5] ZygoteRules v0.2.5
  [6e34b625] Bzip2_jll v1.0.8+1
  [7cc45869] Enzyme_jll v0.0.102+0
  [1d5cc7b8] IntelOpenMP_jll v2024.0.2+0
  [dad2f222] LLVMExtra_jll v0.0.29+0
  [856f044c] MKL_jll v2024.0.0+0
  [efe28fd5] OpenSpecFun_jll v0.5.5+0
  [f50d1b31] Rmath_jll v0.4.0+0
⌅ [fb77eaff] Sundials_jll v5.2.2+0
  [0dad84c5] ArgTools v1.1.1
  [56f22d72] Artifacts
  [2a0f44e3] Base64
  [ade2ca70] Dates
  [8ba89e20] Distributed
  [f43a241f] Downloads v1.6.0
  [7b1f6079] FileWatching
  [9fa8497b] Future
  [b77e0a4c] InteractiveUtils
  [4af54fe1] LazyArtifacts
  [b27032c2] LibCURL v0.6.4
  [76f85450] LibGit2
  [8f399da3] Libdl
  [37e2e46d] LinearAlgebra
  [56ddb016] Logging
  [d6f4376e] Markdown
  [a63ad114] Mmap
  [ca575930] NetworkOptions v1.2.0
  [44cfe95a] Pkg v1.10.0
  [de0858da] Printf
  [9abbd945] Profile
  [3fa0cd96] REPL
  [9a3f8284] Random
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization
  [1a1011a3] SharedArrays
  [6462fe0b] Sockets
  [2f01184e] SparseArrays v1.10.0
  [10745b16] Statistics v1.10.0
  [4607b0f0] SuiteSparse
  [fa267f1f] TOML v1.0.3
  [a4e569a6] Tar v1.10.0
  [8dfed614] Test
  [cf7118a7] UUIDs
  [4ec0a83e] Unicode
  [e66e0078] CompilerSupportLibraries_jll v1.1.0+0
  [deac9b47] LibCURL_jll v8.4.0+0
  [e37daf67] LibGit2_jll v1.6.4+0
  [29816b5a] LibSSH2_jll v1.11.0+1
  [c8ffd9c3] MbedTLS_jll v2.28.2+1
  [14a3606d] MozillaCACerts_jll v2023.1.10
  [4536629a] OpenBLAS_jll v0.3.23+4
  [05823500] OpenLibm_jll v0.8.1+2
  [bea87d4a] SuiteSparse_jll v7.2.1+1
  [83775a58] Zlib_jll v1.2.13+1
  [8e850b90] libblastrampoline_jll v5.8.0+1
  [8e850ede] nghttp2_jll v1.52.0+1
  [3f19e933] p7zip_jll v17.4.0+2
Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated -m`
```

  - Output of `versioninfo()`

```julia
Julia Version 1.10.2
Commit bd47eca2c8 (2024-03-01 10:14 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 12 × Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake)
Threads: 12 default, 2 interactive, 7 GC (on 12 virtual cores)
```

**Additional context**

There was a similar issue #907

### PR DESCRIPTION
**Pull request by prbzrg**
Fixes #1027

## Checklist

- [ ] Appropriate tests were added
- [x] Any code changes were done in a way that does not break public API
- [x] All documentation related to code changes were updated
- [x] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [x] Any new documentation only uses public API

### CODE REVIEW

**Comment by prbzrg** [comment]
I will wait for tests result, and then add a test.
I reduced the MRE to:
```julia
using DifferentialEquations, SciMLSensitivity, Zygote

function f(du, u, p, t)
    du .= 2 * u
    nothing
end

r = rand(Float32, 2, 2)
ps = rand(Float32, 2)

function f2(x)
    prob = ODEProblem(f, r, (0.0f0, 1.0f0), x)
    sol = solve(prob; sensealg = InterpolatingAdjoint(; autodiff = true, autojacvec = true))
    sum(last(sol.u))
end

f2(ps)
Zygote.gradient(f2, ps)
```
Where should I add the tests?

**Comment by prbzrg** [comment]
`codecov/codecov-action` is failing on a test.

**Comment by prbzrg** [comment]
Failed tests seem irrelevant.

**Comment by ChrisRackauckas** [comment]
Can you add a test that covers this?

**Comment by prbzrg** [comment]
The problem can limit usage of poly algorithm, I prefer someone expert in this package do it, so we can be sure this issue is really fixed.

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/SciMLSensitivity.jl/pull/1031 is the right way to do it.

**Pull request closed without merging**
