### PR TITLE
refactor: cleanup deps and replace SparseDiffTools with SciMLJacobianOperators

### PR DESCRIPTION
**Pull request by avik-pal**

### CODE REVIEW

**Comment by avik-pal** [comment]
I think we should drop the NonlinearSolve dep in DiffEqCallbacks a weakdep as a breaking change

**Comment by avik-pal** [comment]
Tests for steadystateadjoint pass locally. We need to wait for the following:

- [ ] SciMLJacobianOperators to be registered (EOD today)
- [ ] OptimizationBase still does support Enzyme 0.13

**Comment by avik-pal** [comment]
We are getting there, we need

`add SteadyStateDiffEq#avik-pal-patch-1 ModelingToolkit#master OptimizationBase#main`

**Comment by ChrisRackauckas** [comment]
Looks like shadowing is failing?

**Comment by avik-pal** [comment]
yeah, typo in refactor. Should be fixed now. The docs are broken but Vaibhav has a open PR for that so I am not touching it atm.

**Comment by ChrisRackauckas** [comment]
Shit didn't mean to click that. There was still an error in shadowing?

**Comment by avik-pal** [comment]
Could that be from any of the packages being unlocked from upgrading? The only change in the shadowing was `@unpack` to `(; `. Quite a few of the packages while allowed to update weren't being tested in CI due to compat issues.

**Pull request merged**
