### PR TITLE
Test master

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@frankschae can you take a look at this?

**Comment by frankschae** [comment]
The kwarg `allow_f_increases` works for me locally. Where do I find OptimizationOptimJL?

```
got unsupported keyword argument "allow_f_increases"
 __map_optimizer_args(::SciMLBase.OptimizationProblem, 
::Optim.AbstractOptimizer; callback, maxiters, maxtime, abstol, reltol) 
at 
~/.cache/julia-buildkite-plugin/depots/ea52448d-f230-4619-b27a-2d98107bd215/packages/OptimizationOptimJL/MgZBn/src/OptimizationOptimJL.jl:16 
```

**Comment by ChrisRackauckas** [comment]
It's a sublibrary of Optimization.jl @Vaibhavdixit02 why does this keep popping up on people's computers? What the compat thing that's keeping things back?

**Comment by Vaibhavdixit02** [comment]
I don't think there is anything holding it back, it should be fixed in the latest release. I couldn't find the stack trace with that error, could you link it, I'll check kf there's any compat holding it back?

**Comment by ChrisRackauckas** [comment]
It's just the manifest.

**Comment by frankschae** [comment]
I was trying to get rid of the Assertion to handle
https://discourse.julialang.org/t/diffeq-continuouscallback-not-callable-errors/88198/4
by filtering the times to match those of the forward.

```julia
if sol.retcode == :Terminated
    # handle bounds errors: if one saves at other times, there can be more or less time points in the primal solution
    # than in the solution using dual numbers:
    indxs = findall(t -> t ∈ ts, _sol.t)
    _du = @view du[indxs]
else
    _du = du
end
```
This doesn't work out if one only uses part of the solution in a subsequent loss function.

For example, our test case
```julia
function loss(u0, p; sensealg=nothing, save_start=false, save_everystep=false)
    _prob = remake(prob, u0=u0, p=p)
    # saving arguments can have a huge influence here
    sol = solve(_prob, Tsit5(), reltol=tol, abstol=tol, sensealg=sensealg,
        callback=cb_t,
        save_start=save_start, save_everystep=save_everystep)
    res = sol.u[end]
    g(res, p, nothing)
end

Zygote.gradient((u0, p) -> loss(u0, p,
        sensealg=ForwardDiffSensitivity(),
        save_start=true,
        save_everystep=true),
    u0, p)
``` 
would return a wrong gradient with respect to `p`.

**Comment by ChrisRackauckas** [comment]
`if sol.retcode == ReturnCode.Terminated`, see how the return codes changed: https://scimlbase.sciml.ai/stable/interfaces/Solutions/#retcodes . I guess that might've made this package hit the wrong branch is the cause of the regression? It does have fallbacks for `==` but it sounds like it didn't handle the Terminated case well.

**Comment by ChrisRackauckas** [comment]
Why would that filtering be incorrect?

**Comment by frankschae** [comment]
> I guess that might've made this package hit the wrong branch is the cause of the regression?

Yes. 

> Why would that filtering be incorrect?

I'll try to figure that out today -- there is still a size mismatch between the backpropagated sensitivities from AD and the filtered forward sensitivities.

i.e. for the last case
```
size(_du) = (20,)
size(Δ) = (2, 22)
```
below.

```
# save_start = false, save_everystep=false
du0
ts = [5.018020622077737]
_sol.t = [5.018020622077737, 5.0378766080905795]
indxs = [1]
du = [[4.541560445342201e-5 0.0; 2.2618223653906948e-5 1.7915714560884677e-7], [4.367597819994558e-5 0.0; 2.1753273181707798e-5 1.6943183653054882e-7]]
_du = [[4.541560445342201e-5 0.0; 2.2618223653906948e-5 1.7915714560884677e-7]]
Δ = [-1.0000452782776872; -1.7500226004441823;;]
size(_du) = (1,)
size(Δ) = (2, 1)
dp
ts = [5.018020622077737]
_sol.t = [5.018020622077737, 5.8452214345031335]
indxs = [1]
du = [[0.4999776046402572 0.49975747975691365 0.0 0.0; 0.12498878953475437 0.12488995034370243 0.24997757906950874 0.06248892746984276], [0.49999505424586965 0.49994392889852557 0.0 0.0; 0.12499762341098473 0.12497434103827809 0.24999524682196947 0.06249728405769909]]
_du = [[0.4999776046402572 0.49975747975691365 0.0 0.0; 0.12498878953475437 0.12488995034370243 0.24997757906950874 0.06248892746984276]]
Δ = [-1.0000452782776872; -1.7500226004441823;;]
size(_du) = (1,)
size(Δ) = (2, 1)

# save_start = true, save_everystep=false

du0
ts = [0.0, 5.018020622077737]
_sol.t = [0.0, 5.018020622077737, 5.0378766080905795]
indxs = [1, 2]
du = [[1.0 0.0; 0.0 1.0], [4.541560445342201e-5 0.0; 2.2618223653906948e-5 1.7915714560884677e-7], [4.367597819994558e-5 0.0; 2.1753273181707798e-5 1.6943183653054882e-7]]
_du = [[1.0 0.0; 0.0 1.0], [4.541560445342201e-5 0.0; 2.2618223653906948e-5 1.7915714560884677e-7]]
Δ = [0.0 -1.0000452782776872; 0.0 -1.7500226004441823]
size(_du) = (2,)
size(Δ) = (2, 2)
dp
ts = [0.0, 5.018020622077737]
_sol.t = [0.0, 5.018020622077737, 5.8452214345031335]
indxs = [1, 2]
du = [[0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0], [0.4999776046402572 0.49975747975691365 0.0 0.0; 0.12498878953475437 0.12488995034370243 0.24997757906950874 0.06248892746984276], [0.49999505424586965 0.49994392889852557 0.0 0.0; 0.12499762341098473 0.12497434103827809 0.24999524682196947 0.06249728405769909]]
_du = [[0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0], [0.4999776046402572 0.49975747975691365 0.0 0.0; 0.12498878953475437 0.12488995034370243 0.24997757906950874 0.06248892746984276]]
Δ = [0.0 -1.0000452782776872; 0.0 -1.7500226004441823]
size(_du) = (2,)
size(Δ) = (2, 2)

# save_start = true, save_everystep=true

du0
ts = [0.0, 9.999999999999999e-5, 0.0010999999999999998, 0.011099999999999997, 0.05403001902489014, 0.1204545017963673, 0.19827555547902923, 0.2980200494994499, 0.41505800253294817, 0.5552781982728943, 0.7186855655050756, 0.9107791282990413, 1.1357743771420952, 1.401902880002128, 1.7167842255753185, 2.08388478222719, 2.5042512063650606, 2.9884671485411225, 3.5515353132857705, 4.216766880680338]
_sol.t = [0.0, 9.999999999999999e-5, 0.0010999999999999998, 0.011099999999999997, 0.04857734109561221, 0.05403001902489014, 0.11390355879413705, 0.1204545017963673, 0.19260391310882957, 0.19827555547902923, 0.2874989977458538, 0.2980200494994499, 0.39732345241783806, 0.41505800253294817, 0.5237620939374833, 0.5552781982728943, 0.667472663178697, 0.7186855655050756, 0.8309702469437518, 0.9107791282990413, 1.0172246133815657, 1.1357743771420952, 1.2308381674958704, 1.401902880002128, 1.4775106569080863, 1.7167842255753185, 1.7656028717060666, 2.08388478222719, 2.105986194294021, 2.5042512063650606, 2.511040041972011, 2.9884671485411225, 2.989827817937452, 3.5515353132857705, 3.5533679831863636, 4.216766880680338, 4.224392467582856, 5.0378766080905795, 5.0378766080905795]
indxs = [1, 2, 3, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36]
du = [[1.0 0.0; 0.0 1.0], [0.9998000199984503 0.0; 9.99700083231814e-5 0.9996000799818039], [0.9978024182018934 0.0; 0.0010963766178037082 0.995609664966286], [0.9780446054655405 0.0; 0.010736696591811373 0.9565712122819177], [0.9074156342908306 0.0; 0.042006248336585054 0.8234031376176605], [0.897573705188488 0.0; 0.04596758957360739 0.8056385260412733], [0.7962778333697109 0.0; 0.08110970907612242 0.634058415217466], [0.7859131362518768 0.0; 0.08412686119764717 0.6176594138565823], [0.6803092366166393 0.0; 0.10874424833414349 0.462820739948352], [0.6726358947900444 0.0; 0.11009842236697007 0.45243905005610396], [0.5627060002942222 0.0; 0.12303387222596009 0.3166382558423019], [0.5509891752697376 0.0; 0.12370008333856285 0.3035890085926116], [0.451740722486257 0.0; 0.1238353115706167 0.20407009934502351], [0.43599867456089514 0.0; 0.12295206416855005 0.19009454622379487], [0.3508052198923444 0.0; 0.11387010118860424 0.12306501751513606], [0.32937555573924726 0.0; 0.11044412186973648 0.10848731199977439], [0.2631725960803043 0.0; 0.09695586191976063 0.06926087224078317], [0.23755123863843383 0.0; 0.09056121363630137 0.056428811365831236], [0.1897704316896834 0.0; 0.07687809696158444 0.03601423776651449], [0.16177317018309614 0.0; 0.06780245338639795 0.026168263410300218], [0.1307525749311115 0.0; 0.05682729034444951 0.01709799424221245], [0.10315196447201261 0.0; 0.04625677602882242 0.010638412414367797], [0.08529201521101658 0.0; 0.03900762476731979 0.007276765676376822], [0.06057889253554321 0.0; 0.028454766322707825 0.003669359890127471], [0.05207781604014999 0.0; 0.024681757643357196 0.002714300753435548], [0.03227176847866595 0.0; 0.015614500908715353 0.0010427666612352058], [0.02927003780337541 0.0; 0.014205540252208292 0.0008589572989587826], [0.015487425454810222 0.0; 0.007622779489135129 0.00024186647653989997], [0.014817823159376095 0.0; 0.007298101566626514 0.000221620026123002], [0.0066820145051544036 0.0; 0.003317848367843991 4.631776946638047e-5], [0.0065919104494845115 0.0; 0.0032734098726293587 4.509070422575375e-5], [0.0025381010113755026 0.0; 0.0012653212809784211 7.45844941867579e-6], [0.002531203733621016 0.0; 0.001261892753998547 7.418225623938463e-6], [0.0008243090960422213 0.0; 0.00041157116922824064 1.1667575857448702e-6], [0.0008212938002702159 0.0; 0.00041006769780508185 1.158404660056783e-6], [0.000219222714913045 0.0; 0.0001094730835850927 2.7654774285841134e-7], [0.0002159114694775278 0.0; 0.00010782109938634694 2.69270704832885e-7], [4.367597819994558e-5 0.0; 2.1753273181707798e-5 1.6943183653054882e-7], [4.367597819994558e-5 0.0; 2.1753273181707798e-5 1.6943183653054882e-7]]
_du = [[1.0 0.0; 0.0 1.0], [0.9998000199984503 0.0; 9.99700083231814e-5 0.9996000799818039], [0.9978024182018934 0.0; 0.0010963766178037082 0.995609664966286], [0.9780446054655405 0.0; 0.010736696591811373 0.9565712122819177], [0.897573705188488 0.0; 0.04596758957360739 0.8056385260412733], [0.7859131362518768 0.0; 0.08412686119764717 0.6176594138565823], [0.6726358947900444 0.0; 0.11009842236697007 0.45243905005610396], [0.5509891752697376 0.0; 0.12370008333856285 0.3035890085926116], [0.43599867456089514 0.0; 0.12295206416855005 0.19009454622379487], [0.32937555573924726 0.0; 0.11044412186973648 0.10848731199977439], [0.23755123863843383 0.0; 0.09056121363630137 0.056428811365831236], [0.16177317018309614 0.0; 0.06780245338639795 0.026168263410300218], [0.10315196447201261 0.0; 0.04625677602882242 0.010638412414367797], [0.06057889253554321 0.0; 0.028454766322707825 0.003669359890127471], [0.03227176847866595 0.0; 0.015614500908715353 0.0010427666612352058], [0.015487425454810222 0.0; 0.007622779489135129 0.00024186647653989997], [0.0066820145051544036 0.0; 0.003317848367843991 4.631776946638047e-5], [0.0025381010113755026 0.0; 0.0012653212809784211 7.45844941867579e-6], [0.0008243090960422213 0.0; 0.00041157116922824064 1.1667575857448702e-6], [0.000219222714913045 0.0; 0.0001094730835850927 2.7654774285841134e-7]]
Δ = [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 -1.0000452782776872; 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 -1.7500226004441823]
size(_du) = (20,)
size(Δ) = (2, 22)
dp
ts = [0.0, 9.999999999999999e-5, 0.0010999999999999998, 0.011099999999999997, 0.05403001902489014, 0.1204545017963673, 0.19827555547902923, 0.2980200494994499, 0.41505800253294817, 0.5552781982728943, 0.7186855655050756, 0.9107791282990413, 1.1357743771420952, 1.401902880002128, 1.7167842255753185, 2.08388478222719, 2.5042512063650606, 2.9884671485411225, 3.5515353132857705, 4.216766880680338]
_sol.t = [0.0, 9.999999999999999e-5, 0.0010999999999999998, 0.011099999999999997, 0.05403001902489014, 0.055864330587053444, 0.1204545017963673, 0.12599815069158224, 0.19827555547902923, 0.20818298019401482, 0.2980200494994499, 0.3143419461581076, 0.41505800253294817, 0.43957674672108216, 0.5552781982728943, 0.5909837740259076, 0.7186855655050756, 0.7690086990082844, 0.9107791282990413, 0.9805803986002757, 1.1357743771420952, 1.2311182313194062, 1.401902880002128, 1.530712507558287, 1.7167842255753185, 1.8884257458045648, 2.08388478222719, 2.3107003431137176, 2.5042512063650606, 2.8036233361956855, 2.9884671485411225, 3.3810351976126127, 3.5515353132857705, 4.060493366594319, 4.216766880680338, 4.868136392269197, 5.8452214345031335, 5.8452214345031335]
indxs = [1, 2, 3, 4, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35]
du = [[0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0], [9.999000066663332e-5 9.998666766661257e-9 0.0 0.0; 4.999000116656628e-9 3.332666739994023e-13 9.998000233313256e-9 3.332500113322087e-13], [0.001098790886845514 1.2082267965747887e-6 0.0 0.0; 6.036707065073959e-7 4.4269177999942564e-10 1.2073414130147918e-6 4.424484066157949e-10], [0.01097769671614836 0.00012140158325607289 0.0 0.0; 6.025491262123789e-5 4.4587900679857955e-7 0.00012050982524247578 4.434153248579786e-7], [0.05121314685825143 0.0027172225637609525 0.0 0.0; 0.0013113935342141069 4.7217747666368635e-5 0.0026227870684282137 4.596920911468632e-5], [0.05285656031748655 0.0028978225467312987 0.0 0.0; 0.001396908285118199 5.2002988247450244e-5 0.002793816570236398 5.058231074058754e-5], [0.1070434304192962 0.012376656906991235 0.0 0.0; 0.005729152514505752 0.0004591759389898692 0.011458305029011503 0.00043282309345292903], [0.1113761933436216 0.01344443309111895 0.0 0.0; 0.00620233308674 0.0005198834588194777 0.01240466617348 0.0004887426813841605], [0.16368205060711088 0.03031479969209819 0.0 0.0; 0.01339591669077568 0.0017614831552734132 0.02679183338155136 0.001600234797177378], [0.1702805503046888 0.03299660017365657 0.0 0.0; 0.014497746317036587 0.0020005537697916883 0.028995492634073174 0.0018090356020288097], [0.22450540524088866 0.06029959285250283 0.0 0.0; 0.025201357499702925 0.00494843892654847 0.05040271499940585 0.00429453951773015], [0.23335339149494455 0.06571698502795102 0.0 0.0; 0.02722695004811623 0.0056315424658592555 0.05445390009623246 0.004851780392704145], [0.2820006448629238 0.10103590175412401 0.0 0.0; 0.039762196725091146 0.010755754151970831 0.07952439345018229 0.008868185561250316], [0.2924329030986182 0.10994962199913079 0.0 0.0; 0.042758605732637574 0.012216205266927795 0.08551721146527515 0.009968165962045073], [0.33531218344540964 0.1524170264771905 0.0 0.0; 0.05621709199133927 0.01999142124725595 0.11243418398267854 0.015557944198442778], [0.3466626038678628 0.16542293104540146 0.0 0.0; 0.060087699637115195 0.022623765885585487 0.12017539927423039 0.01736077416856819], [0.3812243259225016 0.21049934472427542 0.0 0.0; 0.07266584292375629 0.0325838294383814 0.14533168584751258 0.023831876224234536], [0.3925966718763063 0.22740883250971874 0.0 0.0; 0.07706644233257354 0.03663797392228583 0.15413288466514707 0.02632056768801899], [0.41911340609980385 0.2717729047211267 0.0 0.0; 0.087827660783498 0.04805879157706533 0.175655321566996 0.03292248991698358], [0.4296523872684716 0.2916901687473378 0.0 0.0; 0.0923011531263087 0.05354393124736004 0.1846023062526174 0.03589027645881486], [0.4484242038491583 0.33126514102018506 0.0 0.0; 0.10054154778413193 0.06509102272596054 0.20108309556826387 0.041727995214539626], [0.4573777354708696 0.3524331916370775 0.0 0.0; 0.10459794878458226 0.07161864703395633 0.2091958975691645 0.0447879470829716], [0.46971122290341705 0.3847828020348499 0.0 0.0; 0.11031355304641995 0.0820778479710049 0.2206271060928399 0.049328918652646665], [0.4765891130183434 0.40492149480535494 0.0 0.0; 0.11356948353716045 0.08889126386551703 0.2271389670743209 0.052045073455961974], [0.48386553451240466 0.42845879435498857 0.0 0.0; 0.11706222111896909 0.09716717605852516 0.23412444223793819 0.055073670549809335], [0.4885519172080967 0.4453197358844041 0.0 0.0; 0.11934236386035393 0.10331750408184819 0.23868472772070787 0.05712278963831434], [0.4922583573713576 0.45998264091522695 0.0 0.0; 0.12115874718429977 0.10883257327331382 0.24231749436859953 0.058797967178875504], [0.4950793654707869 0.4723476219696462 0.0 0.0; 0.12255243886687715 0.11362137211794579 0.2451048777337543 0.060115014697182924], [0.49666116676221794 0.47992939071397167 0.0 0.0; 0.12333606525774655 0.11662863009923925 0.2466721305154931 0.060866459890159236], [0.4981630146785469 0.4878733030325319 0.0 0.0; 0.12408354985652927 0.11985310165973656 0.24816709971305853 0.06159442752198269], [0.49873274727281297 0.49115318500308197 0.0 0.0; 0.12436719836453003 0.12120939413701086 0.24873439672906006 0.06187241830551801], [0.49942008233717805 0.4955103609387831 0.0 0.0; 0.12471036700410723 0.12304481346528438 0.24942073400821446 0.062211925447556715], [0.49958895524902736 0.4966693007128362 0.0 0.0; 0.12479459047762934 0.12354005987878883 0.24958918095525867 0.06229534973185167], [0.4998499986879889 0.4986429290581715 0.0 0.0; 0.12492507898853328 0.1243963855405524 0.24985015797706656 0.06242529549984743], [0.49989094527178557 0.49897494212640636 0.0 0.0; 0.12494548824226501 0.12454198282093813 0.24989097648453001 0.06244563016338898], [0.49996935115909885 0.4996800677910809 0.0 0.0; 0.12498472357027114 0.12485531032526934 0.24996944714054228 0.062484710329088006], [0.49999505424586965 0.49994392889852557 0.0 0.0; 0.12499762341098473 0.12497434103827809 0.24999524682196947 0.06249728405769909], [0.49999505424586965 0.49994392889852557 0.0 0.0; 0.12499762341098473 0.12497434103827809 0.24999524682196947 0.06249728405769909]]
_du = [[0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0], [9.999000066663332e-5 9.998666766661257e-9 0.0 0.0; 4.999000116656628e-9 3.332666739994023e-13 9.998000233313256e-9 3.332500113322087e-13], [0.001098790886845514 1.2082267965747887e-6 0.0 0.0; 6.036707065073959e-7 4.4269177999942564e-10 1.2073414130147918e-6 4.424484066157949e-10], [0.01097769671614836 0.00012140158325607289 0.0 0.0; 6.025491262123789e-5 4.4587900679857955e-7 0.00012050982524247578 4.434153248579786e-7], [0.05121314685825143 0.0027172225637609525 0.0 0.0; 0.0013113935342141069 4.7217747666368635e-5 0.0026227870684282137 4.596920911468632e-5], [0.1070434304192962 0.012376656906991235 0.0 0.0; 0.005729152514505752 0.0004591759389898692 0.011458305029011503 0.00043282309345292903], [0.16368205060711088 0.03031479969209819 0.0 0.0; 0.01339591669077568 0.0017614831552734132 0.02679183338155136 0.001600234797177378], [0.22450540524088866 0.06029959285250283 0.0 0.0; 0.025201357499702925 0.00494843892654847 0.05040271499940585 0.00429453951773015], [0.2820006448629238 0.10103590175412401 0.0 0.0; 0.039762196725091146 0.010755754151970831 0.07952439345018229 0.008868185561250316], [0.33531218344540964 0.1524170264771905 0.0 0.0; 0.05621709199133927 0.01999142124725595 0.11243418398267854 0.015557944198442778], [0.3812243259225016 0.21049934472427542 0.0 0.0; 0.07266584292375629 0.0325838294383814 0.14533168584751258 0.023831876224234536], [0.41911340609980385 0.2717729047211267 0.0 0.0; 0.087827660783498 0.04805879157706533 0.175655321566996 0.03292248991698358], [0.4484242038491583 0.33126514102018506 0.0 0.0; 0.10054154778413193 0.06509102272596054 0.20108309556826387 0.041727995214539626], [0.46971122290341705 0.3847828020348499 0.0 0.0; 0.11031355304641995 0.0820778479710049 0.2206271060928399 0.049328918652646665], [0.48386553451240466 0.42845879435498857 0.0 0.0; 0.11706222111896909 0.09716717605852516 0.23412444223793819 0.055073670549809335], [0.4922583573713576 0.45998264091522695 0.0 0.0; 0.12115874718429977 0.10883257327331382 0.24231749436859953 0.058797967178875504], [0.49666116676221794 0.47992939071397167 0.0 0.0; 0.12333606525774655 0.11662863009923925 0.2466721305154931 0.060866459890159236], [0.49873274727281297 0.49115318500308197 0.0 0.0; 0.12436719836453003 0.12120939413701086 0.24873439672906006 0.06187241830551801], [0.49958895524902736 0.4966693007128362 0.0 0.0; 0.12479459047762934 0.12354005987878883 0.24958918095525867 0.06229534973185167], [0.49989094527178557 0.49897494212640636 0.0 0.0; 0.12494548824226501 0.12454198282093813 0.24989097648453001 0.06244563016338898]]
Δ = [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 -1.0000452782776872; 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 -1.7500226004441823]
size(_du) = (20,)
size(Δ) = (2, 22)
```

**Pull request merged**
