### PR TITLE
Fix Test Failures

### PR DESCRIPTION
**Pull request by avik-pal**

### CODE REVIEW

**Comment by avik-pal** [comment]
@frankschae for the diffeq test failure it seems like the reverselosscallback `time` is going down to 0 which is causing the indexing error.

```julia
_t = Float32[0.0, 0.062241733, 0.19261953, 0.44402307, 0.7661728, 1.0]
(cur_time, t) = (Base.RefValue{Int64}(6), Float32[0.0, 0.062241733, 0.19261953, 0.44402307, 0.7661728, 1.0])
(cur_time, t) = (Base.RefValue{Int64}(5), Float32[0.0, 0.062241733, 0.19261953, 0.44402307, 0.7661728, 1.0])
(cur_time, t) = (Base.RefValue{Int64}(4), Float32[0.0, 0.062241733, 0.19261953, 0.44402307, 0.7661728, 1.0])
(cur_time, t) = (Base.RefValue{Int64}(3), Float32[0.0, 0.062241733, 0.19261953, 0.44402307, 0.7661728, 1.0])
(cur_time, t) = (Base.RefValue{Int64}(2), Float32[0.0, 0.062241733, 0.19261953, 0.44402307, 0.7661728, 1.0])
(cur_time, t) = (Base.RefValue{Int64}(1), Float32[0.0, 0.062241733, 0.19261953, 0.44402307, 0.7661728, 1.0])
(cur_time, t) = (Base.RefValue{Int64}(0), Float32[0.0, 0.062241733, 0.19261953, 0.44402307, 0.7661728, 1.0])
```

**Comment by avik-pal** [comment]
@ChrisRackauckas this handles the main failures we were seeing. The remaining in Core3 are from DAEs but all of the adjoint methods seem to fail there, not sure what caused that.

**Comment by frankschae** [comment]
Do we know what change caused that? I think the last time that we got such an indexing error, it was save_positions not handled correctly.

**Comment by avik-pal** [comment]
Not sure, the tests were not running for sometime it seems, it was activating an incorrect env

**Review by ChrisRackauckas — APPROVED** [review]

**Pull request merged**
