### PR TITLE
Remove Deps:  `StochasticDiffEq` and `OrdinaryDiffEq`

### LINKED ISSUE #1095: Depending on `OrdinaryDiffEq`?
I tried to replace `OrdinaryDiffEq` by `OrdinaryDiffEqDefault` in my code, but because of deps, it's still there:
```julia
 pkg> why OrdinaryDiffEq
  SciMLSensitivity → OrdinaryDiffEq
  SciMLSensitivity → StochasticDiffEq → OrdinaryDiffEq
```

### PR DESCRIPTION
**Pull request by prbzrg**
Fixes #1095

### CODE REVIEW

**Comment by prbzrg** [comment]
What do we do about `StochasticDiffEq.alg_interpretation`?

**Comment by ChrisRackauckas** [comment]
We can make that a trait in SciMLBase and have StochasticDiffEq extend it.

**Comment by ChrisRackauckas** [comment]
Okay yeah the `alg_interpretation` needs to move to be https://github.com/SciML/SciMLBase.jl/blob/master/src/alg_traits.jl a SciMLBase trait that is extended by StochasticDiffEq

**Comment by ChrisRackauckas** [comment]
Bump the SciMLBase and StochasticDiffEq minors.

**Comment by ChrisRackauckas** [comment]
Thanks for seeing this through!

**Pull request merged**
