### PR TITLE
handle diffusion functions that do not depend on the parameters

### PR DESCRIPTION
**Pull request by frankschae**
Fixes the `MethodError: no method matching vec(::Nothing)` in #697.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Add a test?

**Comment by ChrisRackauckas** [comment]
https://buildkite.com/julialang/diffeqsensitivity-dot-jl/builds/1549#01826942-6c6d-4737-b50f-0b1d8ccfadef/624-945

**Comment by frankschae** [comment]
Shadowing methods failure seems to originate from https://github.com/SciML/SciMLSensitivity.jl/pull/698/files. Fix it here or separate PR?

**Comment by ChrisRackauckas** [comment]
Just fix it here. Sorry I missed that.

**Pull request merged**
