### PR TITLE
Try fixing the 2nd callback test set

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Looks like that was it, thanks.

**Comment by ChrisRackauckas** [comment]
Note @acoh64 that we should probably do this with GaussAdjoint too since that is checkpointing.

**Comment by acoh64** [comment]
It looks like the change was in the one line of `callback_tracking.jl`. I can add a check for `GaussAdjoint` too. Were there any changes to how the checkpointing is done?

**Comment by ChrisRackauckas** [comment]
Nope, no changes to checkpointing.

**Pull request merged**
