### PR TITLE
chore: reinstate repack

### PR DESCRIPTION
**Pull request by DhairyaLGandhi**
## Checklist

- [ ] Appropriate tests were added
- [ ] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [ ] Any new documentation only uses public API
  
## Additional context

Add any other context about the problem here. solves #1146

### CODE REVIEW

**Comment by DhairyaLGandhi** [comment]
@AayushSabharwal could the `restructure` adjoint have introduced the failures in Core 5?

**Comment by AayushSabharwal** [comment]
The logs it's showing me are truncated to after line 5471, I can't see the error

**Comment by DhairyaLGandhi** [comment]
Perhaps this is more useful https://github.com/SciML/SciMLSensitivity.jl/actions/runs/11778287917/job/32804415075?pr=1147

**Comment by AayushSabharwal** [comment]
I don't think it's `ArrayInterface.restructure`. I added an `error()` in the adjoint, and it still gives the same result as CI.

**Pull request merged**
